packages:
  - jq
  - gpg
  - tree
  - unzip

runcmd:
  - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.7+k3s1 sh -
  - mkdir -p /home/ubuntu/.kube/
  - cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/.kube/config
  - chown ubuntu:ubuntu /home/ubuntu/.kube/config
  - k3s completion bash > /etc/bash_completion.d/k3s
  - echo "export KUBECONFIG=/home/ubuntu/.kube/config" | tee -a /home/ubuntu/.bashrc
  - echo "alias k=\'kubectl\'" | tee -a /home/ubuntu/.bashrc
#  - sudo apt install jq -y
#  - sudo apt install gpg
  - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  - sudo apt update && sudo apt install vault

  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - helm completion bash > /etc/bash_completion.d/helm
  - runuser -l ubuntu -c "helm repo add hashicorp https://helm.releases.hashicorp.com"

  - kubectl completion bash > /etc/bash_completion.d/kubectl
  - curl -sL "https://releases.hashicorp.com/vault-k8s/1.1.0/vault-k8s_1.1.0_linux_$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64).zip" | zcat > /usr/local/bin/vault-k8s
  - chmod +x /usr/local/bin/vault-k8s

write_files:
- path: /home/ubuntu/vault-overrides.yaml
  content: |
    server:
      image:
        repository: hashicorp/vault-enterprise
        tag: 1.12.1-ent
      enterpriseLicense:
        secretName: vault-ent-license
      affinity: ""
      ha:
        enabled: true
        replicas: 1
        apiAddr: null
        clusterAddr: null

        raft:
          enabled: true
          setNodeId: true
    ui:
      enabled: true
      publishNotReadyAddresses: true
      activeVaultPodOnly: false
      serviceType: "LoadBalancer"
      serviceNodePort: null
      externalPort: 8200
      targetPort: 8200
  owner: 'ubuntu:ubuntu'
  permissions: '0400'
  defer: true
- path: /home/ubuntu/license.hclic
  content: |
    <license here>
  owner: 'ubuntu:ubuntu'
  permissions: '0666'
  defer: true
- path: /home/ubuntu/write-license.sh
  content: |
    #!/bin/bash
    read -p "Enter Vault license key: " VAULT_LICENSE
    echo $VAULT_LICENSE > /home/ubuntu/license.hclic
    SECRET=$(cat license.hclic); kubectl create secret generic vault-ent-license --from-literal="license=${SECRET}"
    helm install vault hashicorp/vault --values vault-overrides.yaml
    sleep 2
    until [[ $VAULT_POD_STATE == "Running" ]]
    do
      VAULT_POD_STATE=$(kubectl get pod $MY_POD | awk 'FNR==2{printf $3}')
      echo "Not running. Pod is currently: $VAULT_POD_STATE"
      sleep 1
    done
    echo "Vault is ready, proceeding to unseal and init!"
    kubectl exec vault-0 -- vault operator init -key-shares=1 -key-threshold=1 -format=json > cluster-keys.json
  owner: 'ubuntu:ubuntu'
  permissions: '0755'
  defer: true
