server:
  image:
    repository: hashicorp/vault-enterprise
    tag: 1.12.1-ent
  enterpriseLicense:
    secretName: vault-ent-license
  affinity: ""
  ha:
    enabled: true
    replicas: 1

    apiAddr: null

    clusterAddr: null

    raft:

      enabled: true
      setNodeId: true
ui:

  enabled: true
  publishNotReadyAddresses: true
  activeVaultPodOnly: false
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 8200
  targetPort: 8200
